### ISSUE TITLE
Bump wrap to jpeg9c

### ISSUE THREAD

**Issue by fzwoch** [mesonbuild/libjpeg#5]
I have made a `9c` branch based upon `9a` here:

https://github.com/fzwoch/libjpeg/tree/9c

It just bumps the source tarball to `jpeg9c`, changes the version hints from `9a` to `9c` and adds a new `jpeg_dep` object which was previously missing and uses it for linking the applications.

Unfortunately I seem unable to create a pull request which would create a new branch. So I'm not sure what to do to include it into `wrapdb`.

**Comment by sarum9in** [comment]
You did the right thing: opening an issue.
Branch `9c` is ready, please create a pull request.
