### ISSUE TITLE
Current source URL rejects Python-urllib user-agent.

### ISSUE THREAD

**Issue by JPTIZ** [mesonbuild/libjpeg#9]
When you try to use the current wrap, meson fails building with the message:

```
ERROR: could not get http://ijg.org/files/jpegsrc.v9c.tar.gz is the internet available?
```

The reason is that http://ijg.org/files/jpegsrc.v9c.tar.gz currently rejects requests coming from "Python-urllib" user-agent.

Changing the source upstream should resolve this issue.

**Comment by JPTIZ** [comment]
I **finally** found a reliable URL to use: https://github.com/ITNative/libjpeg/archive/libjpeg-9c-90.9.3.zip (from "Download zip" at https://github.com/ITNative/libjpeg/tree/libjpeg-9c-90.9.3).

Since it is a mirror from 9c, I think it is reliable _enough_. Not the best of bests (something that give us each version so we could update to 9d easily would be even better), but...it is what I have for now.

**Comment by xclaesse** [comment]
Note that you can now use `source_fallback_url` and `patch_fallback_url` to make your wraps more reliable. Those tarballs have thousands mirrors you can use.

**Comment by JPTIZ** [comment]
> Note that you can now use `source_fallback_url` and `patch_fallback_url` to make your wraps more reliable. Those tarballs have thousands mirrors you can use.

That's a good point. Although for now @eli-schwartz has pointed another solution, I could have this in mind for later wraps.

**Comment by eli-schwartz** [comment]
The problem isn't the reliability, the problem is the wrapped primary url is always downloaded by meson, and meson fails 100% of the time because meson's default urllib user agent is blacklisted.

Wraps need to work by default, not just in their fallbacks. :D
